version: "3.9"

services:
  postgres:
    container_name: localPostgresSQLDB
    image: postgres
    environment:
      POSTGRES_DB: "local_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "12345"
    ports:
      - "5332:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d # Для инициализационных скриптов, если нужны
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookclub-app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/local_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: "true"
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
      - app-uploads:/app/uploads # Том для загружаемых файлов
    restart: unless-stopped

volumes:
  postgres-data: # Именованный том для данных PostgreSQL
  app-uploads: # Именованный том для загружаемых файлов
